### ISSUE TITLE
Problems running the first exercise (Chapter1) in windows

### ISSUE THREAD

**Issue by KansaiUser** [PacktPublishing/Machine-Learning-Engineering-with-MLflow#14] opened 2022-05-19 14:01 UTC
I am starting to read the book 
In _Getting Started with MLflow_ you got a very simple docker file.
I am trying to run it in my windows 10 machine
There are several problems but when I run 
`docker run -p 8888:8888 -p 5000:5000 -v %cd%:/home/jovyan/ -it chapter_1_homlflow
`
from the cmd, it gets running but in the end I got an error

```
>docker run -p 8888:8888 -p 5000:5000 -v %cd%:/home/jovyan/ -it chapter_1_homlflow
Entered start.sh with args: jupyter lab
Executing the command: jupyter lab
[I 2022-05-19 13:37:21.107 ServerApp] jupyterlab | extension was successfully linked.
[W 2022-05-19 13:37:21.121 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-05-19 13:37:21.121 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-05-19 13:37:21.121 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2022-05-19 13:37:21.129 ServerApp] nbclassic | extension was successfully linked.
[I 2022-05-19 13:37:21.154 ServerApp] Writing Jupyter server cookie secret to /home/jovyan/.local/share/jupyter/runtime/jupyter_cookie_secret
[W 2022-05-19 13:37:21.160 ServerApp] Permissions assignment failed for secure file: '/home/jovyan/.local/share/jupyter/runtime/jupyter_cookie_secret'. Got '0o655' instead of '0o0600'.
[I 2022-05-19 13:37:21.208 ServerApp] notebook_shim | extension was successfully loaded.
[I 2022-05-19 13:37:21.210 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.9/site-packages/jupyterlab
[I 2022-05-19 13:37:21.210 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2022-05-19 13:37:21.218 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-05-19 13:37:21.833 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-05-19 13:37:21.834 ServerApp] Serving notebooks from local directory: /home/jovyan
[I 2022-05-19 13:37:21.835 ServerApp] Jupyter Server 1.17.0 is running at:
[I 2022-05-19 13:37:21.835 ServerApp] http://03086fb5b986:8888/lab?token=04777eb1ad3263ce654af5fd1bda277f822a73b8a83d0c43
[I 2022-05-19 13:37:21.835 ServerApp]  or http://127.0.0.1:8888/lab?token=04777eb1ad3263ce654af5fd1bda277f822a73b8a83d0c43
[I 2022-05-19 13:37:21.835 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-lab", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/jupyter_server/extension/application.py", line 594, in launch_instance
    serverapp.start()
  File "/opt/conda/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 2757, in start
    self.start_app()
  File "/opt/conda/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 2687, in start_app
    self.write_server_info_file()
  File "/opt/conda/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 2503, in write_server_info_file
    with secure_write(self.info_file) as f:
  File "/opt/conda/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/opt/conda/lib/python3.9/site-packages/jupyter_core/paths.py", line 903, in secure_write
    raise RuntimeError(
RuntimeError: Permissions assignment failed for secure file: '/home/jovyan/.local/share/jupyter/runtime/jpserver-7.json'. Got '0o655' instead of '0o0600'.

```
How can I run this very simple example?

**Comment by nebelgrau77** [comment] 2022-05-27 19:37
Same here. Just got the book, trying the first example, same problem also on an Ubuntu machine. 

Follow-up: found this long explanation here, but it didn't help me very much: [[Kernel won't start, throws "Permissions assignment failed for secure file" error](https://github.com/jupyter/notebook/issues/5058) - not sure how to implement it here.

Basically the problem is in the actual content of the folder, because running the container without the -v option works, but then of course we don't have access to the other files. What is happening is that Jupyter at some point expects the permission level to be set to 0o600, but instead it is 0o677. Changing the file permission manually with `chmod` or even deleting the contents of `.local/share/jupyter/runtime` doesn't help, as the files keep getting recreated with 0o677 permissions.


**WORKAROUND**: add `ENV JUPYTER_ALLOW_INSECURE_WRITES=true` at the end of the `Dockerfile`. You'll get a warning that insecure writes have been enabled, but it will work.

**Comment by nebelgrau77** [comment] 2022-07-17 08:04
I'm using this opportunity to learn some more about Docker, and I put together my own little setup for the very first examples from Chapter01. Comments and contributions are welcome, I hope this helps someone:

https://github.com/nebelgrau77/dockerized_notebook/tree/chapter01

**Comment by nlauchande** [comment] 2023-02-25 13:11
@nebelgrau77 : I am relooking at this repo and trying to revive it . Do you mind if i adopt your work above into this repo ?

**Comment by nlauchande** [comment] 2023-02-25 14:59
This is closed as @nebelgrau77 work around works , i will be busy incorporating on this repo.

**Closed as completed by nlauchande** 2023-02-25 14:59 UTC

**Comment by nebelgrau77** [comment] 2023-02-26 13:12
> @nebelgrau77 : I am relooking at this repo and trying to revive it . Do you mind if i adopt your work above into this repo ?

Sure, feel free to use it :)
